services:
  - type: web
    name: epsumstock-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://epsum:5432/epsumstockmanagement
      - key: DATABASE_USERNAME
        value: your-db-username
      - key: DATABASE_PASSWORD
        value: your-db-password
      - key: MAIL_USERNAME
        value: epsummessi@gmail.com
      - key: MAIL_PASSWORD
        value: zdoe oafa nlnc hqfs
