services:
  - type: web
    name: epsumstock-app
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DATABASE_USERNAME
        value: ${DATABASE_USERNAME}
      - key: DATABASE_PASSWORD
        value: ${DATABASE_PASSWORD}
      - key: MAIL_USERNAME
        value: ${MAIL_USERNAME}
      - key: MAIL_PASSWORD
        value: ${MAIL_PASSWORD}

databases:
  - name: epsumstock-db
    plan: starter
    databaseName: epsumstockmanagement
    user: postgres
    ipAllowList: []  # allow all by default, or add your own IPs
